// Trinket table — ORIGINAL CONTENT.
//
// Source / licensing: the PHB d100 trinket table is NOT in SRD 5.1 and is
// not CC-licensed. This file is a fresh 100-entry trinket table authored
// for this project. Some thematic conventions (small uncanny objects with
// implied stories) follow widely shared tabletop tradition, but every entry
// is original prose — nothing was copied from PHB, DMG, or any non-SRD
// table.

export const TRINKETS: readonly string[] = [
  'A brass key shaped like a sleeping fox. It is warm to the touch when handled in daylight.',
  'A folded paper bird with handwriting in the inside crease that is not in any language you recognise.',
  'A small wooden box that hums faintly when set down on stone and falls silent on wood.',
  'A pocketwatch frozen at four minutes past three; the seconds hand twitches when a lie is told within ten feet.',
  'A silver ring engraved with a date forty years before you were born.',
  'A glass bead that holds a single white feather you have never been able to remove.',
  'A scrap of black silk that smells faintly of the sea even after years inland.',
  'A copper coin with a hole through the middle; the rim is worn smooth from being held.',
  'A child\'s tooth wrapped in red thread.',
  'A small brass bell with no clapper.',
  'A bone whistle that produces no sound a human can hear, but dogs always turn to look.',
  'A folded handkerchief with a stranger\'s initials embroidered in dark green.',
  'A glass vial of grey sand from a beach that no one in your town can identify.',
  'A tin badge stamped with a number, eleven, and the word "Apprentice".',
  'A small soft pouch of dried petals that never lose their colour.',
  'A pair of dice that always sum to seven, however they fall.',
  'A wax seal in the shape of an owl; the wax never melts.',
  'A button carved from horn, with a tiny crack the shape of a mountain.',
  'A small porcelain doll with one painted eye open and the other closed.',
  'A green ribbon long enough to wrap a wrist three times, frayed at one end.',
  'A scrap of map showing a coastline you have never seen, with a single inland mark labelled "here".',
  'A black feather tied with red string.',
  'A small framed silhouette of a person whose face you cannot quite remember.',
  'A polished river stone with a single rune carved on the back.',
  'A locket containing two strands of hair, one grey, one auburn.',
  'A folded handbill announcing a play that closed before you were born.',
  'A wooden spoon worn smooth by a hand smaller than yours.',
  'A brass thimble engraved with a phrase in another tongue: roughly, "mend lightly".',
  'A child\'s drawing on yellowed paper, of a house with a single window and no door.',
  'A tin soldier missing the head; the body is painted a colour that does not match any uniform.',
  'A small bag of dried herbs that smells of woodsmoke and someone you used to know.',
  'A coil of fishing line that knots itself into the shape of a heart when held in still water.',
  'A handful of buttons of mismatched make, strung on a single hair-thin chain.',
  'A wax-stoppered bottle of clear water that tastes faintly of salt and copper.',
  'A square of black velvet that catches no dust, however long it sits.',
  'A small mirror that fogs when held by anyone but its owner.',
  'A shred of grey wool, the kind woven by a guild that no longer exists.',
  'A folded letter addressed to you, but never sent, and not in your handwriting.',
  'A pebble that fits perfectly in the hollow at the base of your throat.',
  'A short length of silver chain with one link mended in copper.',
  'A piece of bark with a tiny door carved into it, no bigger than a thumbnail.',
  'A small ceramic cup with a chip in the rim and a name inside the bowl: "Lys".',
  'A bone needle threaded with a single black hair.',
  'A folded scrap of cloth dyed in two colours that nobody you know uses together.',
  'A round flat stone with a single eye drawn on it in white paint.',
  'A brass tag from a beast collar, with the name "Cleff" stamped into it.',
  'A leather lace tied with seven knots.',
  'A glass marble that shows the faint shape of a tree inside, no matter the angle.',
  'A small wooden top that always spins for exactly seventeen seconds.',
  'A pressed flower whose colour fades when seen by lamplight.',
  'A pair of laces from a child\'s shoe, knotted in the middle.',
  'A small dented locket with no clasp; it cannot be opened without breaking.',
  'A handful of dried beans, each painted with a different number from one to nine.',
  'A folded scrap of a coat-of-arms you cannot identify.',
  'A short carved bone in the shape of a fish, with one scale missing.',
  'A copper token reading "Good for one cup" with no shop name.',
  'A folded piece of paper that, when unfolded, contains only the word "no".',
  'A small wooden whistle that, when blown, makes a sound exactly like a crow.',
  'A scrap of parchment with the partial address of a place you have never been.',
  'A small clay figurine of a horse with one leg broken off and reattached.',
  'A wrapped bundle of letters tied with green ribbon, all addressed to a name you have never heard.',
  'A small leather pouch containing seven smooth black stones.',
  'A faded blue button missing its centre thread.',
  'A folded scrap of cloth that smells faintly of incense even after washing.',
  'A small framed engraving of a constellation you cannot place.',
  'A glass vial half-full of a clear, viscous liquid that does not evaporate.',
  'A square of dark cloth with a single white star embroidered in the corner.',
  'A small brass figurine of a hare standing on its hind legs.',
  'A bone die with five sides, one of which is unmarked.',
  'A copper bracelet hammered flat and engraved with the word "remember".',
  'A folded piece of parchment with the recipe for a soup you do not know.',
  'A scrap of leather punched with three holes in a triangle.',
  'A tiny brass key on a leather thong, too small for any lock you have seen.',
  'A small wooden box containing a single dried beetle of an unfamiliar species.',
  'A glass jar with a folded piece of paper inside that reads only "I am sorry".',
  'A polished black stone with a single white vein in the shape of a hand.',
  'A scrap of red silk that bears, faintly, the smell of pipe smoke.',
  'A folded paper boat with the word "Lys" inked on the underside of the hull.',
  'A small brass coin from a foreign mint; the face shows a saint you do not know.',
  'A folded handkerchief embroidered with the silhouette of a tower.',
  'A bone button carved into the face of a sleeping child.',
  'A glass bead containing a single seed that will not sprout when planted.',
  'A scrap of velvet ribbon faded from blue to grey.',
  'A small bottle of ink that, when opened, smells faintly of pine.',
  'A copper ring engraved with three notches on the inside band.',
  'A leather glove for the left hand only, with the index finger mended in different leather.',
  'A folded handkerchief with a bloodstain dried to a soft brown.',
  'A small clay whistle in the shape of a fish, which produces no sound at all.',
  'A folded letter sealed with green wax, addressed to "the next traveller".',
  'A scrap of vellum with the words "stand still until the bells stop" written in faded ink.',
  'A pressed leaf from a tree that does not grow in this region.',
  'A bone die with the numerals in a script you do not recognise.',
  'A folded scrap of cloth bearing a soldier\'s name and rank in old embroidery.',
  'A small jar of clear oil that smells of bread and old leather.',
  'A small framed lock of pale hair, very fine, very long.',
  'A short length of red ribbon tied around an iron nail.',
  'A small wooden disc carved with the moon in its waning crescent.',
  'A folded piece of parchment with three names written down and two of them crossed out.',
  'A copper compass needle that points not north but to your dominant hand.',
  'A small leather pouch of dried lavender that smells of someone who used to hold it.',
  'A glass bead containing a tiny scrap of dried moss.',
  'A wax-sealed paper cone of salt from a shore you have never visited.',
  'A silver thimble engraved with a constellation that isn\'t in the night sky.',
  'A small tin box containing three dried teeth from an unknown beast.',
  'A brass pocket watch with thirteen hours on the face.',
  'A wooden comb missing every third tooth.',
  'A rusted iron key that is inexplicably heavy.',
  'A small glass vial of water that never freezes, even in winter.',
  'A velvet ribbon that changes color depending on the angle of the sun.',
  'A smooth black stone with a hole perfectly through the center.',
  'A piece of chalk that only writes in blue, no matter what color it appears.',
  'A tiny brass bell that makes a sound like breaking glass.',
  'A bone die that always rolls a five when dropped from a height.',
  'A small leather book filled entirely with sketches of different hands.',
  'A silver coin with the same face on both sides.',
  'A small clay pipe shaped like a curled sleeping dragon.',
  'A glass orb containing a single floating dandelion seed.',
  'A copper ring that leaves a faint green mark on the skin after an hour.',
  'A small wooden carving of an owl with one wing broken off.',
  'A piece of parchment with a map to a place called "Nowhere".',
  'A rusted iron nail with a piece of red thread tied around it.',
  'A small tin whistle that makes no sound when blown.',
  'A silver locket containing a tiny, dried blue flower.',
  'A brass button shaped like a compass rose.',
  'A small wooden box containing a handful of silver sand.',
  'A glass bottle with a tiny ship inside, but the ship is broken.',
  'A copper coin with a hole punched through the center.',
  'A piece of polished driftwood shaped vaguely like a bird.',
  'A silver spoon with a twisted handle.',
  'A small leather pouch containing a single, perfectly round pebble.',
  'A brass key with teeth that form the shape of a keyhole.',
  'A small wooden top that spins for exactly one minute before stopping.',
  'A glass vial containing a single drop of liquid gold.',
  'A copper wire bent into the shape of an infinity symbol.',
  'A small clay figurine of a cat with a cracked ear.',
  'A piece of folded paper that forms a different shape each time you unfold it.',
  'A silver ring with a hidden compartment containing a tiny mirror.',
  'A small wooden box that hums softly when opened.',
  'A glass orb that glows faintly when held in the dark.',
  'A copper coin that always lands on the same side when flipped.',
  'A small tin box containing a collection of miniature swords.',
  'A brass compass that always points to the nearest source of water.',
  'A piece of petrified wood that feels warm to the touch.',
  'A silver locket containing a tiny, intricately carved landscape.',
  'A small wooden flute that plays only three notes.',
  'A glass vial containing a feather that changes color based on the bearer\'s mood.',
  'A copper ring that hums softly when near iron.',
  'A small clay whistle shaped like a bird that sounds like a wolf\'s howl.',
  'A piece of parchment with a single word written on it in invisible ink.',
  'A brass button with a picture of a ship that seems to sail when you turn it.',
  'A small wooden box containing a collection of miniature gears.',
  'A glass orb containing a tiny, floating eye that follows you.',
  'A copper coin that feels cold, no matter how long you hold it.',
  'A small tin box containing a single, perfectly preserved butterfly.',
  'A silver spoon that turns black when dipped in poison.',
  'A piece of polished obsidian shaped like a teardrop.',
  'A brass key that opens any lock, but only once.',
  'A small wooden top that hums a different tune every time you spin it.',
  'A glass vial containing a single drop of a glowing blue liquid.',
  'A copper wire bent into the shape of a labyrinth.',
  'A small clay figurine of a dragon that breathes a tiny puff of smoke when squeezed.',
  'A piece of folded paper that folds itself into a crane when you set it down.',
  'A silver ring that makes you slightly lighter when worn.',
  'A small wooden box that whispers secrets when you open it.',
  'A glass orb that shows a different starry sky than the one above.',
  'A copper coin that always seems to find its way back to you after you spend it.',
  'A small tin box containing a collection of miniature locks.',
  'A brass compass that points to the nearest source of magic.',
  'A piece of amber containing a perfectly preserved snowflake.',
  'A silver locket containing a tiny, glowing ember that never goes out.',
  'A small wooden flute that plays a song you can\'t remember learning.',
  'A glass vial containing a single drop of a potion that makes you forget your own name for a minute.',
  'A copper ring that makes you slightly more persuasive when worn.',
  'A small clay whistle shaped like a wolf that sounds like a bird\'s song.',
  'A piece of parchment with a map that changes depending on who holds it.',
  'A brass button with a picture of a mountain that seems to grow when you turn it.',
  'A small wooden box containing a collection of miniature keys.',
  'A glass orb containing a tiny, floating flame that dances when you sing.',
  'A copper coin that feels heavier than it should.',
  'A small tin box containing a single, perfectly preserved rose.',
  'A silver spoon that makes any food taste slightly sweet.',
  'A piece of polished turquoise shaped like a crescent moon.',
  'A brass key that hums softly when you hold it.',
  'A small wooden top that spins backwards.',
  'A glass vial containing a single drop of a potion that makes you slightly taller for an hour.',
  'A copper wire bent into the shape of a tree.',
  'A small clay figurine of a knight that stands at attention when you look at it.',
  'A piece of folded paper that folds itself into a ship when you set it down on water.',
  'A silver ring that makes you slightly stronger when worn.',
  'A small wooden box that smells like freshly baked bread when you open it.',
  'A glass orb that shows a reflection of you as you were ten years ago.',
  'A copper coin that always lands on edge when flipped.',
  'A small tin box containing a collection of miniature shields.',
  'A brass compass that points to the nearest source of danger.',
  'A piece of jade containing a perfectly preserved insect.',
  'A silver locket containing a tiny, glowing pearl.',
  'A small wooden flute that plays a song you\'ve only ever heard in a dream.',
  'A glass vial containing a single drop of a potion that makes you slightly faster for an hour.',
  'A copper ring that makes you slightly luckier when worn.',
  'A small clay whistle shaped like a bear that sounds like a river.',
  'A piece of parchment with a riddle that changes every time you read it.',
  'A brass button with a picture of a forest that seems to rustle when you turn it.',
];
